version: '2.0'

services:
    intranet:
        image: "intranet_dev:latest"
        ports: 
            - "80:80/tcp"
        volumes:
            - ./src:/var/www/html
        user: ${CURRENT_UID}

    reminder:
        image: "intranet_dev:latest"

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080