version: '3.0'

services:
    intranet:
        image: "intranet_dev:latest"
        ports: 
            - "80:80/tcp"

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080