version: '2.0'

services:
    intranet:
        image: "intranet_dev:latest"
        ports: 
            - "80:80/tcp"
        volumes:
            - ./html:/var/www/html
        user: ${CURRENT_UID}
        #command: bash -c "while true; do sleep 2; df -h; done"
    reminder:
        image: "intranet_dev:latest"

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080